// <auto-generated />
using System;
using MLCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MLCore.Migrations
{
    [DbContext(typeof(TrainsDbContext))]
    partial class TrainsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MLCore.Models.Trains", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bod1Cis");

                    b.Property<string>("Bod1Naz");

                    b.Property<int>("Bod2Cis");

                    b.Property<string>("Bod2Naz");

                    b.Property<int?>("CasCesty");

                    b.Property<int>("Dlzka");

                    b.Property<string>("Druh");

                    b.Property<int?>("GvdCasCesty");

                    b.Property<DateTime?>("GvdOdch");

                    b.Property<DateTime?>("GvdPrich");

                    b.Property<int>("Hmot");

                    b.Property<string>("Loko");

                    b.Property<int?>("MeskanieOdchod");

                    b.Property<int?>("MeskaniePrichod");

                    b.Property<DateTime?>("Odch");

                    b.Property<int>("PocNaprav");

                    b.Property<int>("PocVoznov");

                    b.Property<DateTime?>("Prich");

                    b.Property<string>("StrojveduciCislo");

                    b.Property<int>("Vlak");

                    b.Property<int>("VlakId");

                    b.HasKey("Id");

                    b.ToTable("Trains");
                });
#pragma warning restore 612, 618
        }
    }
}
